### ISSUE TITLE
directives deps for ChatComponent not registered within bootstrap

### ISSUE THREAD

**Issue by aitboudad** [ngParty/ng-metadata#117]
Here is a plunker that demonstrates the issue:
https://plnkr.co/edit/fLgyeQVJINtQ5u4erkOs?p=preview

**Comment by Hotell** [comment]
Hey @aitboudad , thanks for report.

So first off, this doesn't work in Angular 2 at all :) and for very good reason.

Your app needs to be defined as a component tree. Separating and registering component as other(global) provider, just doesn't make sense. 

You can globally register attribute directives though ( which is reasonable, because for example router directives are meant to be globally available )

here is your "example"  in Angular 2 http://plnkr.co/edit/xFIG6igcMEqMvAMIRxI0?p=preview

Maybe I should throw error if you wanna do this kind of wrong booting, or just don't register the component at all as is Angular 2 doing.

Why do you need this use case?

**Comment by aitboudad** [comment]
Hey :),
I need it in order to register router components, I was thinking that angular2 support it! anyway registring them in app component solve the issue, thanks for your help though.

**Comment by aitboudad** [comment]
@Hotell I have another question here,
the new version of `ui-router` allow using the angular component v1.5, but seems doesn't work with the `ng-metadata` component in case of using `resolve`

Any chance to make compatible the ng-metadata component with the angular one ?
seems they use `bindToController` https://github.com/angular-ui/ui-router/blob/master/src/ng1/statebuilders/views.ts#L91

**Comment by aciccarello** [comment]
@aitboudad, that sounds like it should be a separate issue :wink: 

It would probably help to add some code to demonstrate your use case.

**Comment by aitboudad** [comment]
@aciccarello yep, here is an example: https://plnkr.co/edit/fLgyeQVJINtQ5u4erkOs?p=preview

**Comment by aitboudad** [comment]
closing in favor of #118
