### ISSUE TITLE
make ng-metadata component work with ui-router 

### ISSUE THREAD

**Issue by aitboudad** [ngParty/ng-metadata#118]
see https://github.com/ngParty/ng-metadata/issues/117#issuecomment-232341689 for more details

Plunker to reproduce the issue:: https://plnkr.co/edit/fLgyeQVJINtQ5u4erkOs?p=preview

**Comment by aciccarello** [comment]
Gotcha,

So you would like to make the resolve properties appear as inputs.

```TypeScript
// In ui-router.config.ts
...
    $stateProvider.state({ 
      name: 'help', 
      url: '/help', 
      component: 'help',
      resolve: {
        test: () => 'test'
      }
    });
...
```

```TypeScript
// In help.component.ts
@Component({
  selector: 'help',
  template: `
    <h1>page help (ng-metadata component)</h1>
    <a ui-sref="home">Go to page home</a>
    <p>Input value => {{ $ctrl.test }}</p>
  `
})
export class HelpComponent {
  @Input() test; // never resolved...
}
```

**Comment by Hotell** [comment]
so with all do respect to ui-router author, the API is really unfortunate + "magic" strings and enforces to have  state definitions in multiple places(state definition, component bindings definition), which is pure madness for bigger apps IMHO

I would rather use "old", traditional API for state declarations where you explicitly set type of binding via template like this

```typescript
 $stateProvider.state({ 
      name: 'help', 
      url: '/help', 
      // component: 'help', this is pure evil
      template: '<help [test]="$resolve.test"></help>',
      resolve: {
        test: () => 'test'
      }
    });
```

The outcome is the same and much more maintainable IMHO.

I haven't read through all ui-router source code, but I'm guessing that they are using pre scope binding for this to work, which is going away in later version of angular >=1.6.

Also I'm not very keen on supporting beta release of ui-router and incorporating unstable API to stable ng-metadata/angular 2 API.

Maybe issue should be raised on https://github.com/angular-ui/ui-router. It would be much cleaner if they would render that template I've provided instead of magical scope pre-bind.

**Comment by aitboudad** [comment]
your suggestion looks good to me, 
let's keep it as it's right now thanks again for your help!

**Comment by Hotell** [comment]
you're welcome :+1:

thanks for pointing this out. So I dig more to uiRouter code and found the "problem". you've already provided link to the potential "bug" https://github.com/angular-ui/ui-router/blob/master/src/ng1/statebuilders/views.ts#L91. thing is that ngMetadata creates bindings on the fly(dynamically without angular 1 machinery), so we can provide ng2 template syntax and other nice things, so `bindToController` and `scope` are always empty objects https://github.com/ngParty/ng-metadata/blob/master/src/core/directives/directive_provider.ts#L88

**Comment by christopherthielen** [comment]
>  // component: 'help',  // I'm afraid of magic strings

This approach mirrors the ui-router ng2 approach, except that in ng2, `'help'` would actually be the Component class `Help`. 

>  It would be much cleaner if they would render that template I've provided instead of magical scope pre-bind.

There's no magical scope pre-bind (if I correctly understand what you're suggesting).  We generate a template like `<help test="::$resolve.test"></help>` based on the `component:` value. 

https://github.com/angular-ui/ui-router/blob/master/src/ng1/statebuilders/views.ts#L49-L65

Of course users can write their own templates like you suggested, when desired.  The ng1 `component:` support is really just a little sugar for building a template with resolves bound.

In ui-router for ng2, we map resolve values by name to matching `@Input()`s, much like we do to `bindings:` in ng1.

> thing is that ngMetadata creates bindings on the fly(dynamically without angular 1 machinery)

Can you explain further? I would need some way to introspect the component definition to see what inputs it has, in order to map resolve values.  I currently do that by getting the component directive from the injector.  At what point do the bindings get defined, and where?

**Comment by Hotell** [comment]
Many thanks @christopherthielen for making things clear. I've read your code more thoroughly, and you are right ofc 👍 "problem" is what I've mentioned above

> thing is that ngMetadata creates bindings on the fly(dynamically without angular 1 machinery), so we can provide ng2 template syntax and other nice things, so bindToController and scope are always empty objects https://github.com/ngParty/ng-metadata/blob/master/src/core/directives/directive_provider.ts#L88

So that's the reason why your mapping doesn't work as with vanilla AngularJS.  I don't use Angular `bindToController` because I do that manually to support ng2 template binging syntax within `controller` ( basically I'm returning new instance of defined class component from `controller` ddo property and within I'm creating bindings etc. https://github.com/ngParty/ng-metadata/blob/master/src/core/directives/directive_provider.ts#L80 )

**Comment by aciccarello** [comment]
I think manually writing the templates isn't that hard of a workaround and is much more explicit. I wonder if there could be an ng-metadata helper function to build the template from the component class annotations.

```TypeScript
 $stateProvider.state({ 
      name: 'help', 
      url: '/help', 
      template: buildUiRouterTemplate(HelpComponent)
      resolve: {
        test: () => 'test'
      }
    });
```

**Comment by aitboudad** [comment]
```ts
import { reflector } from '../../../../node_modules/ng-metadata/src/core/reflection/reflection';

const [annotation] = reflector.annotations(config.component),
  inputs = Object.keys(reflector.propMetadata(config.component));

config.template = `<${annotation.selector}${inputs.map((input) => ` [${input}]="$resolve.${input}"`)}></${annotation.selector}>`;
```

**Comment by aitboudad** [comment]
@aciccarello  :+1:  I think it would be useful
You can use temporary my workaround, I hope it will be useful for you :)

**Comment by danielpiedra** [comment]
I seem to be having an issue related to this, when I'm trying to bind 2way properties through the ui-router template as:

_state.ts_
```
    $stateProvider
        .state('werkbonnen', {
            parent: 'hersteller',
            url: '/werkbonnen',
            template: `<uninu-werkbon-list layout='column' 
                                           layout-fill
                                           [(werkbon-id)]='$ctrl.werkbonId'>
                       </uninu-werkbon-list>`,
        })
```

_component.ts_
```
@Component({
    selector: 'uninu-werkbon-list',
    template: require('./werkbon-list.component.html'),
    styles: require('./werkbon-list.component.scss'),
    providers: [ WerkbonService, AttachRippleEffectDirective, ],
    legacy: {
        transclude: true,
    }
})
export class WerkbonListComponent implements OnInit, OnDestroy, OnChanges {
    private unmutatedWerkbonList: IWerkbon[];
    selectedCardIndex: number;
    selectedWerkbon: IWerkbon;
    werkbonList: IWerkbon[];
    werkbonStatusList: IWerkbonStatus[];

    @Input() werkbonId;

    constructor (
        @Inject('$log')                 private $log: ng.ILogService,
        @Inject('$q')                   private $q: ng.IQService,
        @Inject('$state')               private $state: StateService,
        @Inject('$element')             private $element: ng.IAugmentedJQuery,
        @Inject('$mdInkRipple')         private $mdInkRipple: any,
                                        private werkbonService: WerkbonService,
    ) {} 
....
```

the 'werkbonId' is always undefined when two-way databinding is set, however the same exact code works if one-way binding is set through template
 `[(werkbon-id)]='$ctrl.werkbonId'` => `[werkbon-id]='$ctrl.werkbonId'`

any ideas???

**Comment by mtraynham** [comment]
Soooo, this would be great to have first class support for... but, I took @aitboudad 's solution a step further to handle `@Output`'s as well.

I pulled in the one-time binding prefix generation which is also apparent in [ui-router's templateFactory](https://github.com/angular-ui/ui-router/blob/1.0.4/src/templateFactory.ts#L144).  The `@Output`'s bound function will always have a single argument, which matches `EventEmitter`'s one parameter emit argument.

The only thing this doesn't correctly handle is primitive bindings (`@`) and two-way bindings (`=`).  I think that's ok though, the former is somewhat pointless IMO and the latter is deemed bad practice for components.

```ts
import {version} from 'angular';
import {reflector} from 'ng-metadata/src/core/reflection/reflection';
import {InputMetadata, OutputMetadata} from 'ng-metadata/src/core/directives/metadata_directives';

// Only Angular >= 1.3 supports one-time binding
const prefix: string = version.minor >= 3 ? '::' : '';

function kebobString (camelCase: string): string {
    return camelCase
        // Replace first character
        .replace(/^([A-Z])/, ($1: string) => $1.toLowerCase())
        // Replace the rest
        .replace(/([A-Z])/g, ($1: string) => `-${$1.toLowerCase()}`);
}

function componentTemplate (component: any): string {
    // Component Name
    const [annotation]: any = reflector.annotations(component);
    const componentName: string = kebobString(annotation.selector);
    // Component Params
    const propMetadata: {[key: string]: any[]} = reflector.propMetadata(component);
    const componentParams: string[] = Object.keys(propMetadata).reduce(
        (accumulator: string[], property: string) => {
            // Has @Input binding
            if (propMetadata[property].some((metadata: any) => metadata instanceof InputMetadata)) {
                return accumulator.concat([`[${kebobString(property)}]="${prefix}$resolve.${property}"`]);
            // Has @Output binding
            } else if (propMetadata[property].some((metadata: any) => metadata instanceof OutputMetadata)) {
                return accumulator.concat([`(${kebobString(property)})="$resolve.${property}($event)"`]);
            }
            // Do nothing
            return accumulator;
        },
        []
    );
    // Template
    return `<${componentName} ${componentParams.join(' ')}></${componentName}>}`;
}

export default componentTemplate;
```
