### ISSUE TITLE
question: migration from ng-forward

### ISSUE THREAD

**Issue by david-gang** [ngParty/ng-metadata#122]
Hi,

What would I need to do to migrate from ng-forward to ng-metadata?
Is there a sort of guide line?

Thanks,
David

**Comment by aciccarello** [comment]
I don't think it should be that much of a change if you are already using TypeScript. From looking at the APIs here are some things I notice.

- Import from ng-metadata, usually `ng-metadata/core`, instead of `ng-forward`
- the [`@Inject`](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/decorator.html#inject) decorator is done in the constructor params instead of on the class
- the `@StateConfig` decorator is not supported. Use a [config block](https://hotell.gitbooks.io/ng-metadata/content/docs/recipes/startup-logic.html) instead
- ng-metadata uses a [`provide`](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/function.html#provide) helper to inter-op with classic ng1 modules but it does have a [`bundle`](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/function.html#bundle) function
- The Angular 2 test helpers are not yet implemented (see #93)

It might be good to create a migration document in the ng-forward repo.

**Comment by david-gang** [comment]
Thanks

**Comment by titonobre** [comment]
Last Friday I made de migration from ng-forward to ng-metadata and everything seems to be fine. 

Another tip for those who want to migrate from ng-forward:

- In the templates, the component scope is `$ctrl`, instead of `ctrl`
